2021-07-27 11:30:15,576 - get_all_match_urls.py[line:61] - WARNING: get schedule detail url failed: http://data.champdas.com/match/scheduleDetail-1-2018-10.html
2021-07-27 11:30:15,576 - get_all_match_urls.py[line:62] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /match/scheduleDetail-1-2018-10.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157AD5A0948>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:31:49,783 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 15058, half = 2
2021-07-27 11:31:49,783 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157ADE6BCC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
