2021-07-27 11:38:21,345 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchStaticListAjax.html, match_id = 16569, half = 2
2021-07-27 11:38:21,345 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchStaticListAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F70F14688>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:38:51,891 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 16595, half = 2
2021-07-27 11:38:51,891 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F71FB5388>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:39:34,207 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 16639, half = 1
2021-07-27 11:39:34,207 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F71C33688>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
